In [1]:
import numpy  as np
import pandas as pd

In [5]:
np1 = np.arange(1, 65).reshape(8, 8)
np2 = np.arange(100, 164).reshape(8, 8)
print(np1, "\n\n", np2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]] 

 [[100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115]
 [116 117 118 119 120 121 122 123]
 [124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147]
 [148 149 150 151 152 153 154 155]
 [156 157 158 159 160 161 162 163]]


In [6]:
df1 = pd.DataFrame(data=np1, columns=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])
df2 = pd.DataFrame(data=np2, columns=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])

In [7]:
df1

A   B   C   D   E   F   G   H
0   1   2   3   4   5   6   7   8
1   9  10  11  12  13  14  15  16
2  17  18  19  20  21  22  23  24
3  25  26  27  28  29  30  31  32
4  33  34  35  36  37  38  39  40
5  41  42  43  44  45  46  47  48
6  49  50  51  52  53  54  55  56
7  57  58  59  60  61  62  63  64

In [8]:
df2

A    B    C    D    E    F    G    H
0  100  101  102  103  104  105  106  107
1  108  109  110  111  112  113  114  115
2  116  117  118  119  120  121  122  123
3  124  125  126  127  128  129  130  131
4  132  133  134  135  136  137  138  139
5  140  141  142  143  144  145  146  147
6  148  149  150  151  152  153  154  155
7  156  157  158  159  160  161  162  163

In [9]:
df3 = pd.concat([df1, df2])

In [10]:
df3

A    B    C    D    E    F    G    H
0    1    2    3    4    5    6    7    8
1    9   10   11   12   13   14   15   16
2   17   18   19   20   21   22   23   24
3   25   26   27   28   29   30   31   32
4   33   34   35   36   37   38   39   40
5   41   42   43   44   45   46   47   48
6   49   50   51   52   53   54   55   56
7   57   58   59   60   61   62   63   64
0  100  101  102  103  104  105  106  107
1  108  109  110  111  112  113  114  115
2  116  117  118  119  120  121  122  123
3  124  125  126  127  128  129  130  131
4  132  133  134  135  136  137  138  139
5  140  141  142  143  144  145  146  147
6  148  149  150  151  152  153  154  155
7  156  157  158  159  160  161  162  163

In [13]:
df3.iloc[1]

A     9
B    10
C    11
D    12
E    13
F    14
G    15
H    16
Name: 1, dtype: int32

In [14]:
df3 = pd.concat([df1, df2], ignore_index=True)

In [15]:
df3

A    B    C    D    E    F    G    H
0     1    2    3    4    5    6    7    8
1     9   10   11   12   13   14   15   16
2    17   18   19   20   21   22   23   24
3    25   26   27   28   29   30   31   32
4    33   34   35   36   37   38   39   40
5    41   42   43   44   45   46   47   48
6    49   50   51   52   53   54   55   56
7    57   58   59   60   61   62   63   64
8   100  101  102  103  104  105  106  107
9   108  109  110  111  112  113  114  115
10  116  117  118  119  120  121  122  123
11  124  125  126  127  128  129  130  131
12  132  133  134  135  136  137  138  139
13  140  141  142  143  144  145  146  147
14  148  149  150  151  152  153  154  155
15  156  157  158  159  160  161  162  163

In [21]:
df3.iloc[14]

A    148
B    149
C    150
D    151
E    152
F    153
G    154
H    155
Name: 14, dtype: int32

In [18]:
type(df3.values)

numpy.ndarray

In [22]:
df4 = pd.concat([df1, df2])
df4

A    B    C    D    E    F    G    H
0    1    2    3    4    5    6    7    8
1    9   10   11   12   13   14   15   16
2   17   18   19   20   21   22   23   24
3   25   26   27   28   29   30   31   32
4   33   34   35   36   37   38   39   40
5   41   42   43   44   45   46   47   48
6   49   50   51   52   53   54   55   56
7   57   58   59   60   61   62   63   64
0  100  101  102  103  104  105  106  107
1  108  109  110  111  112  113  114  115
2  116  117  118  119  120  121  122  123
3  124  125  126  127  128  129  130  131
4  132  133  134  135  136  137  138  139
5  140  141  142  143  144  145  146  147
6  148  149  150  151  152  153  154  155
7  156  157  158  159  160  161  162  163

In [23]:
frames = [df1, df2]
df4 = pd.concat(frames, keys=['x', 'y'])
df4

A    B    C    D    E    F    G    H
x 0    1    2    3    4    5    6    7    8
  1    9   10   11   12   13   14   15   16
  2   17   18   19   20   21   22   23   24
  3   25   26   27   28   29   30   31   32
  4   33   34   35   36   37   38   39   40
  5   41   42   43   44   45   46   47   48
  6   49   50   51   52   53   54   55   56
  7   57   58   59   60   61   62   63   64
y 0  100  101  102  103  104  105  106  107
  1  108  109  110  111  112  113  114  115
  2  116  117  118  119  120  121  122  123
  3  124  125  126  127  128  129  130  131
  4  132  133  134  135  136  137  138  139
  5  140  141  142  143  144  145  146  147
  6  148  149  150  151  152  153  154  155
  7  156  157  158  159  160  161  162  163

In [27]:
df4.loc['x'].iloc[4]

A    33
B    34
C    35
D    36
E    37
F    38
G    39
H    40
Name: 4, dtype: int32

In [31]:
df4.iloc[-15]

A     9
B    10
C    11
D    12
E    13
F    14
G    15
H    16
Name: (x, 1), dtype: int32

In [32]:
df4.loc['y']

A    B    C    D    E    F    G    H
0  100  101  102  103  104  105  106  107
1  108  109  110  111  112  113  114  115
2  116  117  118  119  120  121  122  123
3  124  125  126  127  128  129  130  131
4  132  133  134  135  136  137  138  139
5  140  141  142  143  144  145  146  147
6  148  149  150  151  152  153  154  155
7  156  157  158  159  160  161  162  163

In [33]:
df1, df2

(    A   B   C   D   E   F   G   H
 0   1   2   3   4   5   6   7   8
 1   9  10  11  12  13  14  15  16
 2  17  18  19  20  21  22  23  24
 3  25  26  27  28  29  30  31  32
 4  33  34  35  36  37  38  39  40
 5  41  42  43  44  45  46  47  48
 6  49  50  51  52  53  54  55  56
 7  57  58  59  60  61  62  63  64,      A    B    C    D    E    F    G    H
 0  100  101  102  103  104  105  106  107
 1  108  109  110  111  112  113  114  115
 2  116  117  118  119  120  121  122  123
 3  124  125  126  127  128  129  130  131
 4  132  133  134  135  136  137  138  139
 5  140  141  142  143  144  145  146  147
 6  148  149  150  151  152  153  154  155
 7  156  157  158  159  160  161  162  163)

In [34]:
pieces    = {'x':df1, 'y':df2}
df_pieces = pd.concat(pieces) 

In [35]:
df_pieces

A    B    C    D    E    F    G    H
x 0    1    2    3    4    5    6    7    8
  1    9   10   11   12   13   14   15   16
  2   17   18   19   20   21   22   23   24
  3   25   26   27   28   29   30   31   32
  4   33   34   35   36   37   38   39   40
  5   41   42   43   44   45   46   47   48
  6   49   50   51   52   53   54   55   56
  7   57   58   59   60   61   62   63   64
y 0  100  101  102  103  104  105  106  107
  1  108  109  110  111  112  113  114  115
  2  116  117  118  119  120  121  122  123
  3  124  125  126  127  128  129  130  131
  4  132  133  134  135  136  137  138  139
  5  140  141  142  143  144  145  146  147
  6  148  149  150  151  152  153  154  155
  7  156  157  158  159  160  161  162  163

In [36]:
df1.to_csv("df1.csv")
df2.to_csv("df2.csv")

In [37]:
df1 = pd.DataFrame(data=np1, columns=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])
df2 = pd.DataFrame(data=np2, columns=['AA', 'BB', 'CC', 'DD', 'EE', 'FF', 'GG', 'HH'])

In [38]:
df1

A   B   C   D   E   F   G   H
0   1   2   3   4   5   6   7   8
1   9  10  11  12  13  14  15  16
2  17  18  19  20  21  22  23  24
3  25  26  27  28  29  30  31  32
4  33  34  35  36  37  38  39  40
5  41  42  43  44  45  46  47  48
6  49  50  51  52  53  54  55  56
7  57  58  59  60  61  62  63  64

In [39]:
df2

AA   BB   CC   DD   EE   FF   GG   HH
0  100  101  102  103  104  105  106  107
1  108  109  110  111  112  113  114  115
2  116  117  118  119  120  121  122  123
3  124  125  126  127  128  129  130  131
4  132  133  134  135  136  137  138  139
5  140  141  142  143  144  145  146  147
6  148  149  150  151  152  153  154  155
7  156  157  158  159  160  161  162  163

In [42]:
df3 = pd.concat([df1, df2], axis=0)

c:\pyproj\venv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [43]:
df3

A     AA     B     BB     C     CC     D     DD     E     EE     F  \
0   1.0    NaN   2.0    NaN   3.0    NaN   4.0    NaN   5.0    NaN   6.0   
1   9.0    NaN  10.0    NaN  11.0    NaN  12.0    NaN  13.0    NaN  14.0   
2  17.0    NaN  18.0    NaN  19.0    NaN  20.0    NaN  21.0    NaN  22.0   
3  25.0    NaN  26.0    NaN  27.0    NaN  28.0    NaN  29.0    NaN  30.0   
4  33.0    NaN  34.0    NaN  35.0    NaN  36.0    NaN  37.0    NaN  38.0   
5  41.0    NaN  42.0    NaN  43.0    NaN  44.0    NaN  45.0    NaN  46.0   
6  49.0    NaN  50.0    NaN  51.0    NaN  52.0    NaN  53.0    NaN  54.0   
7  57.0    NaN  58.0    NaN  59.0    NaN  60.0    NaN  61.0    NaN  62.0   
0   NaN  100.0   NaN  101.0   NaN  102.0   NaN  103.0   NaN  104.0   NaN   
1   NaN  108.0   NaN  109.0   NaN  110.0   NaN  111.0   NaN  112.0   NaN   
2   NaN  116.0   NaN  117.0   NaN  118.0   NaN  119.0   NaN  120.0   NaN   
3   NaN  124.0   NaN  125.0   NaN  126.0   NaN  127.0   NaN  128.0   NaN   
4   NaN  132.0   NaN  133.0   NaN  134.0   NaN  135.0   NaN  136.0   NaN   
5   NaN  140.0   NaN  141.0   NaN  142.0   NaN  143.0   NaN  144.0   NaN   
6   NaN  148.0   NaN  149.0   NaN  150.0   NaN  151.0   NaN  152.0   NaN   
7   NaN  156.0   NaN  157.0   NaN  158.0   NaN  159.0   NaN  160.0   NaN   

      FF     G     GG     H     HH  
0    NaN   7.0    NaN   8.0    NaN  
1    NaN  15.0    NaN  16.0    NaN  
2    NaN  23.0    NaN  24.0    NaN  
3    NaN  31.0    NaN  32.0    NaN  
4    NaN  39.0    NaN  40.0    NaN  
5    NaN  47.0    NaN  48.0    NaN  
6    NaN  55.0    NaN  56.0    NaN  
7    NaN  63.0    NaN  64.0    NaN  
0  105.0   NaN  106.0   NaN  107.0  
1  113.0   NaN  114.0   NaN  115.0  
2  121.0   NaN  122.0   NaN  123.0  
3  129.0   NaN  130.0   NaN  131.0  
4  137.0   NaN  138.0   NaN  139.0  
5  145.0   NaN  146.0   NaN  147.0  
6  153.0   NaN  154.0   NaN  155.0  
7  161.0   NaN  162.0   NaN  163.0

In [44]:
import pymysql

In [45]:
conn = pymysql.connect('localhost', 'root', '', 'msit')

In [46]:
pd.read_sql_table('students', conn)

NotImplementedError: read_sql_table only supported for SQLAlchemy connectable.

In [47]:
sql = "SELECT * FROM `students`;"
pd.read_sql(sql, conn)

id    fname     lname       city
0   1    Naman  Aggarwal  New Delhi
1   2  Nishant   Chaubey  Jharkhand
2   3    Mohit    Pandhi   Anritsar
3   4   Ashman  Malhotra    Patiala
4   6    Mohit     Kumar  Jagadhari
5   7   Deepak      Bahl      Ropar
6   8   Jagjit     Singh    Panipat