In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.shape

(891, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [16]:
df.Age.isna().sum()

177

In [17]:
df.Cabin.isna().sum()

687

In [18]:
df.shape[0]-df.count()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
nonadf = df.dropna()
nonadf.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [23]:
nonadf.count()

PassengerId    183
Survived       183
Pclass         183
Name           183
Sex            183
Age            183
SibSp          183
Parch          183
Ticket         183
Fare           183
Cabin          183
Embarked       183
dtype: int64

In [25]:
nonadf.shape

(183, 12)

In [26]:
891-183

708

In [27]:
fill_zero_df = df.fillna(0)
fill_zero_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            891
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          891
Embarked       891
dtype: int64

In [28]:
df.Age.mean()

29.69911764705882

In [29]:
fill_zero_df.Age.mean()

23.79929292929293

In [35]:
fill_mean_df = df.Age.fillna(df.Age.mean())   #This will create a series
fill_mean_df.count()

891

In [36]:
fill_mean_df.mean()

29.69911764705882

In [37]:
df.Age.fillna(df.Age.mean(), inplace=True)   # Manipulating the actual DF

In [38]:
df.Age

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
5      29.699118
6      54.000000
7       2.000000
8      27.000000
9      14.000000
10      4.000000
11     58.000000
12     20.000000
13     39.000000
14     14.000000
15     55.000000
16      2.000000
17     29.699118
18     31.000000
19     29.699118
20     35.000000
21     34.000000
22     15.000000
23     28.000000
24      8.000000
25     38.000000
26     29.699118
27     19.000000
28     29.699118
29     29.699118
         ...    
861    21.000000
862    48.000000
863    29.699118
864    24.000000
865    42.000000
866    27.000000
867    31.000000
868    29.699118
869     4.000000
870    26.000000
871    47.000000
872    33.000000
873    47.000000
874    28.000000
875    15.000000
876    20.000000
877    19.000000
878    29.699118
879    56.000000
880    25.000000
881    33.000000
882    22.000000
883    28.000000
884    25.000000
885    39.000000
886    27.000000
887    19.000000
888    29.6991

<hr>

In [40]:
df = pd.read_csv('pima-indians-diabetes.csv', header=None)
df.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [41]:
df.shape

(768, 9)

In [42]:
df.count()

0    768
1    768
2    768
3    768
4    768
5    768
6    768
7    768
8    768
dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
0    768 non-null int64
1    768 non-null int64
2    768 non-null int64
3    768 non-null int64
4    768 non-null int64
5    768 non-null float64
6    768 non-null float64
7    768 non-null int64
8    768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [44]:
df.describe()

0           1           2           3           4           5  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

                6           7           8  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [45]:
df.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [50]:
df[[0]==0].sum()

2953

In [53]:
(df[[0,1,2,3,4,5,6,7,8]]==0).sum()

0    111
1      5
2     35
3    227
4    374
5     11
6      0
7      0
8    500
dtype: int64

In [65]:
df1 = df[[0,1,2,3,4,5,6,7,8]].replace(0, np.NAN)

In [63]:
df.replace(0, np.NAN, inplace=True)

In [67]:
df1.isna().sum()

0    111
1      5
2     35
3    227
4    374
5     11
6      0
7      0
8    500
dtype: int64

In [68]:
df1[0].mean()

4.494672754946728

In [69]:
df1.fillna(df1.mean(), inplace=True)
df1

0      1          2         3           4          5      6   7  \
0     6.000000  148.0  72.000000  35.00000  155.548223  33.600000  0.627  50   
1     1.000000   85.0  66.000000  29.00000  155.548223  26.600000  0.351  31   
2     8.000000  183.0  64.000000  29.15342  155.548223  23.300000  0.672  32   
3     1.000000   89.0  66.000000  23.00000   94.000000  28.100000  0.167  21   
4     4.494673  137.0  40.000000  35.00000  168.000000  43.100000  2.288  33   
5     5.000000  116.0  74.000000  29.15342  155.548223  25.600000  0.201  30   
6     3.000000   78.0  50.000000  32.00000   88.000000  31.000000  0.248  26   
7    10.000000  115.0  72.405184  29.15342  155.548223  35.300000  0.134  29   
8     2.000000  197.0  70.000000  45.00000  543.000000  30.500000  0.158  53   
9     8.000000  125.0  96.000000  29.15342  155.548223  32.457464  0.232  54   
10    4.000000  110.0  92.000000  29.15342  155.548223  37.600000  0.191  30   
11   10.000000  168.0  74.000000  29.15342  155.548223  38.000000  0.537  34   
12   10.000000  139.0  80.000000  29.15342  155.548223  27.100000  1.441  57   
13    1.000000  189.0  60.000000  23.00000  846.000000  30.100000  0.398  59   
14    5.000000  166.0  72.000000  19.00000  175.000000  25.800000  0.587  51   
15    7.000000  100.0  72.405184  29.15342  155.548223  30.000000  0.484  32   
16    4.494673  118.0  84.000000  47.00000  230.000000  45.800000  0.551  31   
17    7.000000  107.0  74.000000  29.15342  155.548223  29.600000  0.254  31   
18    1.000000  103.0  30.000000  38.00000   83.000000  43.300000  0.183  33   
19    1.000000  115.0  70.000000  30.00000   96.000000  34.600000  0.529  32   
20    3.000000  126.0  88.000000  41.00000  235.000000  39.300000  0.704  27   
21    8.000000   99.0  84.000000  29.15342  155.548223  35.400000  0.388  50   
22    7.000000  196.0  90.000000  29.15342  155.548223  39.800000  0.451  41   
23    9.000000  119.0  80.000000  35.00000  155.548223  29.000000  0.263  29   
24   11.000000  143.0  94.000000  33.00000  146.000000  36.600000  0.254  51   
25   10.000000  125.0  70.000000  26.00000  115.000000  31.100000  0.205  41   
26    7.000000  147.0  76.000000  29.15342  155.548223  39.400000  0.257  43   
27    1.000000   97.0  66.000000  15.00000  140.000000  23.200000  0.487  22   
28   13.000000  145.0  82.000000  19.00000  110.000000  22.200000  0.245  57   
29    5.000000  117.0  92.000000  29.15342  155.548223  34.100000  0.337  38   
..         ...    ...        ...       ...         ...        ...    ...  ..   
738   2.000000   99.0  60.000000  17.00000  160.000000  36.600000  0.453  21   
739   1.000000  102.0  74.000000  29.15342  155.548223  39.500000  0.293  42   
740  11.000000  120.0  80.000000  37.00000  150.000000  42.300000  0.785  48   
741   3.000000  102.0  44.000000  20.00000   94.000000  30.800000  0.400  26   
742   1.000000  109.0  58.000000  18.00000  116.000000  28.500000  0.219  22   
743   9.000000  140.0  94.000000  29.15342  155.548223  32.700000  0.734  45   
744  13.000000  153.0  88.000000  37.00000  140.000000  40.600000  1.174  39   
745  12.000000  100.0  84.000000  33.00000  105.000000  30.000000  0.488  46   
746   1.000000  147.0  94.000000  41.00000  155.548223  49.300000  0.358  27   
747   1.000000   81.0  74.000000  41.00000   57.000000  46.300000  1.096  32   
748   3.000000  187.0  70.000000  22.00000  200.000000  36.400000  0.408  36   
749   6.000000  162.0  62.000000  29.15342  155.548223  24.300000  0.178  50   
750   4.000000  136.0  70.000000  29.15342  155.548223  31.200000  1.182  22   
751   1.000000  121.0  78.000000  39.00000   74.000000  39.000000  0.261  28   
752   3.000000  108.0  62.000000  24.00000  155.548223  26.000000  0.223  25   
753   4.494673  181.0  88.000000  44.00000  510.000000  43.300000  0.222  26   
754   8.000000  154.0  78.000000  32.00000  155.548223  32.400000  0.443  45   
755   1.000000  128.0  88.000000  39.00000  110.000000  36.500000  1.057  37   
756   7.00000

In [70]:
df1.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

# Built-in Methods

In [71]:
df1 = df[[0,1,2,3,4,5,6,7,8]].replace(0, np.NAN)
df1.head()

0      1     2     3      4     5      6   7    8
0  6.0  148.0  72.0  35.0    NaN  33.6  0.627  50  1.0
1  1.0   85.0  66.0  29.0    NaN  26.6  0.351  31  NaN
2  8.0  183.0  64.0   NaN    NaN  23.3  0.672  32  1.0
3  1.0   89.0  66.0  23.0   94.0  28.1  0.167  21  NaN
4  NaN  137.0  40.0  35.0  168.0  43.1  2.288  33  1.0

In [72]:
df1.shape

(768, 9)

In [73]:
from sklearn.preprocessing import Imputer

In [74]:
df1.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [77]:
values = df1.values

In [78]:
imputer = Imputer()

c:\pyproj\venv\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [79]:
tranformed_values = imputer.fit_transform(values)

In [80]:
np.isnan(tranformed_values).sum()

0

In [82]:
tranformed_values[4]

array([  4.49467275, 137.        ,  40.        ,  35.        ,
       168.        ,  43.1       ,   2.288     ,  33.        ,
         1.        ])

In [83]:
# Customise Imputer
imp = Imputer(missing_values='NaN', strategy='median', axis=0 )

c:\pyproj\venv\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [84]:
tranformed_values2 = imp.fit_transform(values)

In [85]:
np.isnan(tranformed_values2).sum()

0

In [86]:
tranformed_values2

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   1.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   1.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   1.   ]])

In [87]:
tranformed_values2[4]

array([  4.   , 137.   ,  40.   ,  35.   , 168.   ,  43.1  ,   2.288,
        33.   ,   1.   ])

In [90]:
df[0].median()

4.0