In [1]:
import numpy as np

In [2]:
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)

In [5]:
np1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np1 = np.array([[1, 2, 3],[ 4, 5, 6], [7, 8, 9]])
np1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Identity Matrix

In [8]:
np1 = np.eye(3)

In [9]:
np1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np1 = np.eye(5)

In [11]:
np1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [17]:
np.eye(5, 5, 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.eye(5, 5, 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.eye(5, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [22]:
np.eye(5, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

# Central Tedency

- Mean
- Median
- Mode

In [26]:
np1 = np.random.randint(1, 150, 41)
np1

array([144, 102, 136,  40,  39,  71, 124,  31,  17,  33,  90,  44,  96,
         8,  41,  59,  71,  29,  62, 126, 113,  63,  19,  26,  53, 103,
        66,  24,   2,  42, 135,  83,  92,  60,  12,  98, 118, 140,  13,
        68, 139])

In [27]:
np.mean(np1)

69.07317073170732

In [28]:
np.median(np1)

63.0

In [29]:
from scipy import stats

In [30]:
stats.mode(np1)

ModeResult(mode=array([71]), count=array([2]))

# Linear Algebra

In [32]:
np1 = np.array([[1, 2], [3, 4]])
np1

array([[1, 2],
       [3, 4]])

In [33]:
np.linalg.det(np1)

-2.0000000000000004

In [34]:
np.linalg.inv(np1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [35]:
np.transpose(np1)

array([[1, 3],
       [2, 4]])

In [40]:
np1 = np.array([[1,2], [3, 4]])
np2 = np.array([[2, 1], [4, 3]])
print(np1, "\n\n", np2)

[[1 2]
 [3 4]] 

 [[2 1]
 [4 3]]


In [39]:
np1 * np2

array([[ 2,  2],
       [12, 12]])

In [41]:
np.dot(np1, np2)

array([[10,  7],
       [22, 15]])

# Solve Linear Algebra Problems

In [42]:
mat1 = np.array([[2, 1], [1, 1]])
mat2 = np.array([1, 2])

In [43]:
mat1

array([[2, 1],
       [1, 1]])

In [44]:
mat2

array([1, 2])

In [45]:
np.linalg.solve(mat1, mat2)

array([-1.,  3.])

In [47]:
%%timeit
mat1 = np.array([[2, 1], [1, 1]])
mat2 = np.array([1, 2])
np.linalg.solve(mat1, mat2)

16.5 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
%%timeit
mat1 = np.array([[2, 1], [1, 1]])
mat2 = np.array([1, 2])
np.linalg.solve(mat1, mat2)

16.4 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Insert Update and Delete

In [49]:
np1 = np.array([1, 2, 3])
np1

array([1, 2, 3])

In [50]:
np.append(np1, [10])

array([ 1,  2,  3, 10])

In [51]:
np.append(np1, [20, 30])

array([ 1,  2,  3, 20, 30])

In [52]:
np1 = np.arange(2, 11).reshape(3,3)
np1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
np.append(np1, [10, 20, 30])

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 20, 30])

In [55]:
np.append(np1, [[10, 20, 30]], axis=0)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [10, 20, 30]])

In [56]:
np.append(np1, [[10], [20], [11]], axis=1)

array([[ 2,  3,  4, 10],
       [ 5,  6,  7, 20],
       [ 8,  9, 10, 11]])

In [57]:
# Insert can add data at any index

In [58]:
np1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [59]:
np.insert(np1, 1, 111)

array([  2, 111,   3,   4,   5,   6,   7,   8,   9,  10])

In [60]:
np.insert(np1, 1, 111, axis=0)

array([[  2,   3,   4],
       [111, 111, 111],
       [  5,   6,   7],
       [  8,   9,  10]])

In [61]:
np.insert(np1, 1, 111, axis=1)

array([[  2, 111,   3,   4],
       [  5, 111,   6,   7],
       [  8, 111,   9,  10]])

In [62]:
np.insert(np1, 1, [10, 20, 1], axis=0)

array([[ 2,  3,  4],
       [10, 20,  1],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [63]:
np.insert(np1, 1, [10, 20, 1], axis=1)

array([[ 2, 10,  3,  4],
       [ 5, 20,  6,  7],
       [ 8,  1,  9, 10]])

In [64]:
# Delete

In [65]:
np1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [66]:
np.delete(np1, 2)

array([ 2,  3,  5,  6,  7,  8,  9, 10])

In [67]:
np.delete(np1, 2, axis=0)

array([[2, 3, 4],
       [5, 6, 7]])

In [68]:
np.delete(np1, 2, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [69]:
np.delete(np1, [1, 2], axis=1)

array([[2],
       [5],
       [8]])

# Split Array

In [72]:
np1 = np.arange(48).reshape(6, 8)
np1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [73]:
np.split(np1, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]])]

In [75]:
print(np.split(np1, 2)[0])
print()
print(np.split(np1, 2)[1])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

[[24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]


In [76]:
np.split(np1, 6)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47]])]

In [77]:
np.split(np1, 6, axis=0)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47]])]

In [80]:
np.split(np1, 8, axis=1)

[array([[ 0],
        [ 8],
        [16],
        [24],
        [32],
        [40]]), array([[ 1],
        [ 9],
        [17],
        [25],
        [33],
        [41]]), array([[ 2],
        [10],
        [18],
        [26],
        [34],
        [42]]), array([[ 3],
        [11],
        [19],
        [27],
        [35],
        [43]]), array([[ 4],
        [12],
        [20],
        [28],
        [36],
        [44]]), array([[ 5],
        [13],
        [21],
        [29],
        [37],
        [45]]), array([[ 6],
        [14],
        [22],
        [30],
        [38],
        [46]]), array([[ 7],
        [15],
        [23],
        [31],
        [39],
        [47]])]

In [81]:
np.split(np1, 2, axis=1)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27],
        [32, 33, 34, 35],
        [40, 41, 42, 43]]), array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [36, 37, 38, 39],
        [44, 45, 46, 47]])]

In [83]:
np.split(np1, 4, axis=1)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41]]), array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27],
        [34, 35],
        [42, 43]]), array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29],
        [36, 37],
        [44, 45]]), array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31],
        [38, 39],
        [46, 47]])]

In [84]:
# Concatenation

In [85]:
np1 = np.arange(1, 9).reshape(2, 4)
np1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
np.concatenate((np1, np1), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
np.concatenate((np1, np1), axis=1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [89]:
#Tile

In [90]:
np1 = np.array([1, 2, 3, 4, 5])
np1

array([1, 2, 3, 4, 5])

In [91]:
np.tile(np1, 2)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [92]:
np.tile(np1, 3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [93]:
np1 = np.arange(1, 11).reshape(2, 5)

In [94]:
np1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [95]:
np.tile(np1, 2)

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [96]:
np.tile(np1, 3)

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [99]:
np.tile(np1, (2,1))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [102]:
np.tile(np1, (4,3))

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [103]:
#Repeat

In [104]:
np1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [105]:
np1 = np.array([1, 2, 3])
np1

array([1, 2, 3])

In [106]:
np.repeat(np1, 2)

array([1, 1, 2, 2, 3, 3])

In [107]:
np.repeat(np1, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [108]:
np1 = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])
np1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [109]:
np.repeat(np1, 2)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10])

In [110]:
np.repeat(np1, 2, axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [111]:
np.repeat(np1, 2, axis=1)

array([[ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5],
       [ 6,  6,  7,  7,  8,  8,  9,  9, 10, 10]])