# Numpy

In [1]:
import numpy as np

In [2]:
L1 = [10, 20, 30, 40, 50]
nl1 = np.array(L1)

In [3]:
type(nl1)

numpy.ndarray

In [4]:
nl1 + 10

array([20, 30, 40, 50, 60])

In [5]:
nl1 * 2

array([ 20,  40,  60,  80, 100])

In [6]:
nl1 = np.array([10, 20, 30])
nl2 = np.array([20, 40, 50])
nl1 + nl2

array([30, 60, 80])

In [7]:
nl1 = np.array([10, 20, 30])
nl2 = np.array([20, 40, 50, 500])
nl1 + nl2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [8]:
np1 = np.array([1, 2, 3, 4, 5.0])
np1

array([1., 2., 3., 4., 5.])

In [9]:
np2 = np.array([1, 2, 3, True, False])
np2

array([1, 2, 3, 1, 0])

In [10]:
np3 = np.array([1, 2, 3, "data", "structure"])
np3

array(['1', '2', '3', 'data', 'structure'], dtype='<U11')