In [1]:
import numpy as np

In [5]:
np1 = np.full((5, 2, 3), sum([2, 3]), float)
np1

array([[[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]]])

In [10]:
np1 = np.arange(10, dtype=float)

In [11]:
np1[0] = 90

In [12]:
np1

array([90.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [13]:
np.reciprocal(np1)

array([0.01111111, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
np1 = np.arange(20)
np1[np1>15]

array([16, 17, 18, 19])

In [15]:
np1 = np.arange(1, 50)
np2 = np1[np1>30]

In [16]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
np2

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

IndexError: index 49 is out of bounds for axis 0 with size 49